apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: default
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:v0.5.20
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: OPENAI_API_BASE_URLS
              value: "http://vllm-serve-svc:8000/v1"
            - name: OPENAI_API_KEY
              value: "dummy"
            - name: WEBUI_AUTH
              value: "False"
            - name: ENABLE_OLLAMA_API
              value: "False"
            - name: ENABLE_EVALUATION_ARENA_MODELS
              value: "False"
          volumeMounts:
            - name: webui-volume
              mountPath: /app/backend/data
      volumes:
        - name: webui-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: default
  labels:
    app: open-webui
spec:
  type: LoadBalancer    # Changed from ClusterIP to LoadBalancer
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
